//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerBingo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bingobalota
    {
        public int Bingobalotasid { get; set; }
        public System.DateTime Jgofch { get; set; }
        public string Jgonro { get; set; }
        public string Jgocod { get; set; }
        public string Nrobalota { get; set; }
    
        public virtual Bingotbl Bingotbl { get; set; }
    }
}
