//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerBingo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bingotbl
    {
        public Bingotbl()
        {
            this.Bingobalotas = new HashSet<Bingobalota>();
            this.Bingoganadores = new HashSet<Bingoganadore>();
            this.Bingoreyes = new HashSet<Bingoreye>();
        }
    
        public string Tblnro { get; set; }
        public string Tblb1 { get; set; }
        public string Tblb2 { get; set; }
        public string Tblb3 { get; set; }
        public string Tblb4 { get; set; }
        public string Tblb5 { get; set; }
        public string Tbli1 { get; set; }
        public string Tbli2 { get; set; }
        public string Tbli3 { get; set; }
        public string Tbli4 { get; set; }
        public string Tbli5 { get; set; }
        public string Tbln1 { get; set; }
        public string Tbln2 { get; set; }
        public string Tbln3 { get; set; }
        public string Tbln4 { get; set; }
        public string Tbln5 { get; set; }
        public string Tblg1 { get; set; }
        public string Tblg2 { get; set; }
        public string Tblg3 { get; set; }
        public string Tblg4 { get; set; }
        public string Tblg5 { get; set; }
        public string Tblo1 { get; set; }
        public string Tblo2 { get; set; }
        public string Tblo3 { get; set; }
        public string Tblo4 { get; set; }
        public string Tblo5 { get; set; }
        public bool Tbljuega { get; set; }
        public bool Tblinhabil { get; set; }
        public int Tblanotac { get; set; }
        public int Tblanotaf { get; set; }
        public int Tblganac { get; set; }
        public int Tblganaf { get; set; }
        public string Tblfree { get; set; }
        public string Tblpiram { get; set; }
        public string Tblanota { get; set; }
        public decimal Tblvlrjgo { get; set; }
        public decimal Tblnveces { get; set; }
        public decimal Tblpospira { get; set; }
        public bool Tblandroid { get; set; }
    
        public virtual ICollection<Bingobalota> Bingobalotas { get; set; }
        public virtual ICollection<Bingoganadore> Bingoganadores { get; set; }
        public virtual ICollection<Bingoreye> Bingoreyes { get; set; }
    }
}
