//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerBingo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Bingoganadore
    {
        [Key]
        public int Bingoganid { get; set; }
        public System.DateTime Jgofch { get; set; }
        public string Jgonro { get; set; }
        public string Jgocod { get; set; }
        public int Idusuario { get; set; }
        public string Tblnro { get; set; }
        public bool Tblb1 { get; set; }
        public bool Tblb2 { get; set; }
        public bool Tblb3 { get; set; }
        public bool Tblb5 { get; set; }
        public bool Tbli1 { get; set; }
        public bool Tbli2 { get; set; }
        public bool Tbli3 { get; set; }
        public bool Tbli4 { get; set; }
        public bool Tbli5 { get; set; }
        public bool Tbln1 { get; set; }
        public bool Tbln2 { get; set; }
        public bool Tbln3 { get; set; }
        public bool Tbln4 { get; set; }
        public bool Tbln5 { get; set; }
        public bool Tblg1 { get; set; }
        public bool Tblg2 { get; set; }
        public bool Tblg3 { get; set; }
        public bool Tblg4 { get; set; }
        public bool Tblg5 { get; set; }
        public bool Tblo1 { get; set; }
        public bool Tblo2 { get; set; }
        public bool Tblo3 { get; set; }
        public bool Tblo4 { get; set; }
        public bool Tblo5 { get; set; }
    
        public virtual Bingousuario Bingousuario { get; set; }
        public virtual Bingotbl Bingotbl { get; set; }
    }
}
