//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerBingo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Bingousuario
    {
        public Bingousuario()
        {
            this.Bingoganadores = new HashSet<Bingoganadore>();
            this.Bingoreyes = new HashSet<Bingoreye>();
        }
    
        [Key]
        public int Idusuario { get; set; }
        public string Alias { get; set; }
        public string Macadress { get; set; }
        public string Ip { get; set; }
        public System.DateTime Ultimafechaconexion { get; set; }
        public System.DateTime Ultimafechadejuego { get; set; }
        public decimal Saldoactual { get; set; }
        public string Socsucursal { get; set; }
        public Nullable<double> Gpslatitud { get; set; }
        public Nullable<double> Gpslongitud { get; set; }
        public byte[] Imagenuser { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<Bingoganadore> Bingoganadores { get; set; }
        //public virtual Bingosoc Bingosoc { get; set; }
        public virtual ICollection<Bingoreye> Bingoreyes { get; set; }
    }
}
